### ISSUE TITLE
Splitting demo from add-on

### ISSUE THREAD

**Issue by LucasSnatiago** [BraindeadBZH/godot_card_engine#19]
Can you split the game demo from the add-on using git sub-modules?  I can't use your add-on as a sub-module of my game I need to download the entire repo and get the add-on source code from the demo and add on my game.

**Comment by BraindeadBZH** [comment]
Thank you for your feedback. My primary goal is to provide a framework that works out of the box. As it is today, just dropping the addon in your project will not work. It requires a specific setup of singletons and some initialization code. So I still prefer to provide a fully functional project instead of explaining how to properly install the addon, which prove challenging for some in the past. But I keep your proposal in mind to also offer an option for devs wanting to add CardEngine in existing project.

**Comment by LucasSnatiago** [comment]
Thanks man. I got the idea!
