### ISSUE TITLE
Directory structure way to confusing!

### ISSUE THREAD

**Issue by BigDC** [BraindeadBZH/godot_card_engine#3]
It is very hard to tell what files are the engine and what files are the demo.  I am not sure what is the engine's directories and files, and what is the demo project's directories and files.

May I suggest creating the project file your self and then using this this structure...

**Card_Engine_Demo (project directory)**
```
Structure of "res//" (inside the project directory)
  --the directories and files for the demo (directories and files)
  --addons (directory)
      --card_engine (directory)
         --the directories and files inside of the card engine only (directories and files)
```
This will clearly define what is what.

**Comment by BraindeadBZH** [comment]
The problem with your structure is that the demo files are interfering with the user project files. As I eventually want the framework to be distributed with the Godot's AssetLib I also have to respect the directory structure too. I want to make the demo transparent for who wants to only use the framework. I could have make two separate projects, one for the engine ans the other for the demo, but to me it looked much simpler to distribute altogether.
I know that the Godot team are discussing the way Assets are organized, if they change that I might reevaluate the file structure.
For the moment, an easy way to get it right is if the file is under the "demo" sub-directory then it is a demo file otherwise it is part of the engine.

**Comment by BraindeadBZH** [comment]
I also invite you to read the full documentation (not complete yet) on my personal website: [https://www.braindead.bzh/page/cardengine-home](url). Here I describe more in depth the the file structure. However I think the file structure is irrelevant to the final user as there is no file that needs to be edited inside it.
