### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by artbohr** [BraindeadBZH/godot_card_engine#5]
I think would be cool if you reformatted the project a bit, making the "card engine" folder the main one, the README.md and the LICENSE are not detected by github, because they are not in the main folder, also getting the .gitignore in the main folder, just for the sake of looking more clean and having the readme and the license displayed correctly.

Offtopic; I hope you will continue this project at some point, seems like a really cool project, good job.

**Comment by BraindeadBZH** [comment]
I know the file structure is not optimal but it is due to constraint of the Godot Engine. Especially if I want to put the project in the AssetLib, this is the structure I have to follow. I know the devs at Godot are aware of the issue and might already be working on the different way to handle assets.

I hope too finding the time to continue.
